name: Test

on:
  push:
  pull_request:

jobs:
  Toolchain:
    name: Install Rust toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

  Test:
    name: Test
    needs: [Toolchain]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test
